"""
suspicious_collector.py

Scan all case meta.json files under the cases directory,
apply configurable ratio-based filtering rules, and collect
instance_ids that satisfy any enabled suspicious condition.

Designed to work with meta files generated by meta_builder.

"""

import json
from pathlib import Path

# ================= Configuration =================

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CASES_DIR = PROJECT_ROOT / "cases"
OUTPUT_FILE = PROJECT_ROOT / "Suspicious_instance.json"

FILTER_CONFIG = {
    "total_ratio": {
        "enabled": True,
        "min": 0.0,
        "max": 0.2,
    },
    "added_ratio": {
        "enabled": False,
        "min": 4.0,
        "max": None,
    },
    "removed_ratio_is_null_and_model_removed_gt": {
        "enabled": False,
        "min_removed": 1,
    },
    "file_count_ratio": {
        "enabled": False,
        "min": 1.5,
        "max": None,
    },
}

def active_reason_config():
    reasons = {}

    for name, cfg in FILTER_CONFIG.items():
        if not cfg.get("enabled"):
            continue


        if name in {"total_ratio", "added_ratio", "file_count_ratio"}:
            reasons[name] = {
                "min": cfg.get("min"),
                "max": cfg.get("max"),
            }
        elif name == "removed_ratio_is_null_and_model_removed_gt":
            reasons[name] = {
                "min_removed": cfg.get("min_removed"),
            }

    return reasons

def in_range(value, min_v=None, max_v=None):
    if value is None:
        return False
    if min_v is not None and value < min_v:
        return False
    if max_v is not None and value > max_v:
        return False
    return True


def suspicious_reasons(meta: dict) -> list[str]:

    reasons = []

    model = meta["model_patch_info"]
    ratios = meta.get("ratios", {})

    # ---- total_ratio ----
    cfg = FILTER_CONFIG["total_ratio"]
    if cfg["enabled"]:
        if in_range(ratios.get("total_ratio"), cfg["min"], cfg["max"]):
            reasons.append("total_ratio")

    # ---- added_ratio ----
    cfg = FILTER_CONFIG["added_ratio"]
    if cfg["enabled"]:
        if in_range(ratios.get("added_ratio"), cfg["min"], cfg["max"]):
            reasons.append("added_ratio")

    # ---- removed_ratio is null but model actually removes lines ----
    cfg = FILTER_CONFIG["removed_ratio_is_null_and_model_removed_gt"]
    if cfg["enabled"]:
        if (
            ratios.get("removed_ratio") is None
            and model.get("removed_lines", 0) >= cfg["min_removed"]
        ):
            reasons.append("removed_ratio_is_null_and_model_removed_gt")

    # ---- file_count_ratio ----
    cfg = FILTER_CONFIG["file_count_ratio"]
    if cfg["enabled"]:
        if in_range(ratios.get("touched_file_ratio"), cfg["min"], cfg["max"]):
            reasons.append("file_count_ratio")

    return reasons


def main():
    suspicious_ids = []

    for case_dir in CASES_DIR.iterdir():
        if not case_dir.is_dir():
            continue

        meta_path = case_dir / "meta.json"
        if not meta_path.exists():
            continue

        with open(meta_path, "r", encoding="utf-8") as f:
            meta = json.load(f)

        reasons = suspicious_reasons(meta)
        if reasons:
            suspicious_ids.append(meta["base_info"]["instance_id"])

    suspicious_ids = sorted(set(suspicious_ids))

    output = {
        "Total": len(suspicious_ids),
        "reasons": active_reason_config(),
        "instance_ids": suspicious_ids,
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"[OK] Suspicious cases: {len(suspicious_ids)}")
    print(f"[OK] Active reasons: {', '.join(output['reasons'].keys())}")
    print(f"[OK] Output written to: {OUTPUT_FILE}")



if __name__ == "__main__":
    main()
